const Menuitems = [
  {
    navlabel: true,
    subheader: "MENU",
    icon: "mdi mdi-dots-horizontal",
    href: "Dashboard",
    role: "admin",
    isAdmin: true,
    isSPV: true,
    isStaff: true,
  },
  {
    title: "Dashboard",
    icon: "grid",
    href: "/admin/home",
    collapse: true,
    isAdmin: false,
    isSPV: true,
    isStaff: false,
  },
  {
    title: "Siswa",
    icon: "grid",
    href: "/admin/siswa",
    collapse: true,
    isAdmin: false,
    isSPV: true,
    isStaff: false,
  },
  {
    title: "Laporan",
    icon: "layers",
    href: "/laporan",
    collapse: true,
    isAdmin: true,
    isSPV: true,
    isStaff: true,
    children: [
      {
        title: "Semua",
        icon: "activity",
        href: "/admin/siswa",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Kehadiran",
        icon: "clock",
        href: "/laporan/activity",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Izin",
        icon: "slack",
        href: "/laporan/izin",
        role: "admin",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },

      {
        title: "Cuti",
        icon: "clipboard",
        href: "/laporan/cuti",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },

      {
        title: "Sakit",
        icon: "cloud-lightning",
        href: "/laporan/sakit",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Lembur",
        icon: "clock",
        href: "/laporan/overtime",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Generate",
        icon: "calendar",
        href: "/laporan/generate",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
    ],
  },

  {
    title: "Management",
    icon: "user-check",
    href: "/management",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "User",
        icon: "users",
        href: "/management/user",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Pendaftaran User",
        icon: "user-plus",
        href: "/management/user-v2/register",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Pendaftaran Sendiri",
        icon: "users",
        href: "/management/self-registration",
        isAdmin: true,
      },
      {
        title: "Client Upliner",
        icon: "users",
        href: "/management/client-upliner",
        isAdmin: true,
      },
      {
        title: "Absen Point",
        icon: "target",
        href: "/management/location-point",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Jabatan",
        icon: "briefcase",
        href: "/management/job-level",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Posisi",
        icon: "info",
        href: "/management/position",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Shifting",
        icon: "clock",
        href: "/management/shifting",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Jadwal",
        icon: "calendar",
        href: "/management/schedule",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Event Date",
        icon: "info",
        href: "/management/event-date",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Hari Libur",
        icon: "info",
        href: "/management/holidays",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Departements",
        icon: "globe",
        href: "/management/departemens",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Departements Setting",
        icon: "settings",
        href: "/management/departements-settings",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
    ],
  },
  {
    title: "Perusahaan",
    icon: "user-check",
    href: "/company",
    collapse: true,
    isSuperAdmin: true,
    role: "admin",
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "Perusahaan",
        icon: "compass",
        href: "/company/add-company",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Pengaturan Perusahaan",
        icon: "settings",
        href: "/company/company-setting",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
    ],
  },
];
export default Menuitems;
