export const styleLeft = {
  position: "relative",
  marginLeft: "20px",
  marginBottom: "10px",
  padding: "15px",
  backgroundColor: "#A8DDFD",
  // maxWidth: "50%",
  //height: "50px",
  textAlign: "left",
  font: "400 .9em 'Open Sans', sans-serif",
  border: "1px solid #97C6E3",
  borderRadius: "10px",
  "&:after": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "15px solid #A8DDFD",
    borderLeft: "15px solid transparent",
    borderRight: "15px solid #A8DDFD",
    top: "0",
    left: "-15px",
  },
  "&:before": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "17px solid #97C6E3",
    borderLeft: "16px solid transparent",
    borderRight: "16px solid transparent",
    top: "-0.5px",
    left: "-17px",
  },
};

export const styleRight = {
  position: "relative",
  marginRight: "20px",
  marginBottom: "10px",
  padding: "15px",
  backgroundColor: "#f8e896",
  // maxWidth: "50%",
  //height: "50px",
  textAlign: "left",
  font: "400 .9em 'Open Sans', sans-serif",
  border: "1px solid #dfd087",
  borderRadius: "10px",
  "&:after": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "15px solid #f8e896",
    borderLeft: "15px solid transparent",
    borderRight: "15px solid transparent",
    top: "0",
    right: "-15px",
  },
  "&:before": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "15px solid #dfd087",
    borderLeft: "16px solid transparent",
    borderRight: "16px solid transparent",
    top: "-0.5px",
    right: "-17px",
  },
};

export const styleErrorLeft = {
  backgroundColor: "#f44336",
  color: "white",
  border: "1px solid #f44336",
  "&:after": {
    content: "''",
    borderTop: "15px solid #f44336",
    borderRight: "15px solid #f44336",
  },
  "&:before": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "17px solid #f44336",
    borderLeft: "16px solid transparent",
    borderRight: "16px solid transparent",
    top: "-0.5px",
    left: "-17px",
  },
};

export const styleErrorRight = {
  backgroundColor: "#f44336",
  color: "white",
  border: "1px solid #f44336",
  "&:after": {
    content: "''",
  },
  "&:before": {
    content: "''",
    position: "absolute",
    width: "0",
    height: "0",
    borderTop: "15px solid #f44336",
    borderLeft: "16px solid transparent",
    borderRight: "16px solid transparent",
    top: "-0.5px",
    right: "-17px",
  },
};
